package io.agentshield.controlplane.security.application;

import io.agentshield.controlplane.security.domain.Principal;
import io.agentshield.controlplane.workspace.repository.AppUserRepository;
import io.agentshield.controlplane.workspace.repository.CiTokenRepository;
import io.agentshield.controlplane.workspace.repository.WorkspaceMemberRepository;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.util.HexFormat;
import java.util.Optional;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** Turns credentials into a {@link Principal}, or into nothing. */
@Service
public class AuthenticationService {

    private final AppUserRepository users;
    private final WorkspaceMemberRepository members;
    private final CiTokenRepository ciTokens;
    private final PasswordEncoder passwordEncoder;

    public AuthenticationService(
            AppUserRepository users,
            WorkspaceMemberRepository members,
            CiTokenRepository ciTokens,
            PasswordEncoder passwordEncoder) {
        this.users = users;
        this.members = members;
        this.ciTokens = ciTokens;
        this.passwordEncoder = passwordEncoder;
    }

    @Transactional(readOnly = true)
    public Optional<Principal> authenticateUser(String email, String password) {
        var user = users.findByEmailIgnoreCase(email).orElse(null);
        if (user == null || user.getPasswordHash() == null) {
            // Hash anyway. Returning early for an unknown address makes the response time a
            // reliable oracle for which email addresses have accounts.
            passwordEncoder.matches(password, "$2a$12$invalidinvalidinvalidinvalidinvalidinvalidin");
            return Optional.empty();
        }
        if (!passwordEncoder.matches(password, user.getPasswordHash())) {
            return Optional.empty();
        }

        return members.findMembershipsInOrder(user.getId()).stream()
                .findFirst()
                .map(member -> new Principal(
                        user.getId(),
                        user.getEmail(),
                        member.getWorkspaceId(),
                        member.getRole(),
                        false));
    }

    @Transactional(readOnly = true)
    public Optional<Principal> authenticateCiToken(String token) {
        return ciTokens.findByTokenHash(hash(token))
                .filter(ciToken -> ciToken.isUsable(Instant.now()))
                .map(ciToken -> Principal.forCiToken(ciToken.getWorkspaceId(), ciToken.getId()));
    }

    /**
     * SHA-256 of the presented token.
     *
     * <p>Unsalted and fast on purpose: a CI token is 256 bits of entropy generated by us, not
     * a human-chosen password, so there is nothing to brute-force and nothing to rainbow-table.
     * BCrypt here would add ~250ms to every CI request for no security benefit.
     */
    public static String hash(String token) {
        try {
            var digest = MessageDigest.getInstance("SHA-256");
            return HexFormat.of().formatHex(digest.digest(token.getBytes(StandardCharsets.UTF_8)));
        } catch (NoSuchAlgorithmException exception) {
            throw new IllegalStateException("SHA-256 is required by the JVM specification", exception);
        }
    }
}
